services:
  devenv-volumes:
    image: ${DESKTOP_PLUGIN_IMAGE}
    cap_add:
      - DAC_OVERRIDE
      - FOWNER
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock
    ports:
      - "18180:5678"
