version: "3.7"

services:
  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - ollama

  ollama-web:
    image: vietanhdev/p8hub-ollama-webui
    restart: always
    ports:
      - 3000:80
    networks:
      - ollama

networks:
  ollama:
    driver: bridge

volumes:
  ollama:

